server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: c3VwZXIgbGFyZ2UgY2hhcmFjdGVyIGluIHRoaXMgU2VjcmV0IGxpbmU=